name: Pizza planet CI

on:
  pull_request:
    branches: [main]

jobs:
  pizza-planet-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make install-dependencies

      - name: Start the database
        run: |
          make init-db

      - name: Run format
        run: |
          make format

      - name: Build coverage file
        run: |
          pytest --cache-clear --cov > pytest-coverage.txt
            
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.1
  